# Generated by Django 5.0 on 2024-11-18 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0003_club_miembros'),
        ('eventos', '0002_eventoasistido_usuario_alter_eventoasistido_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoasistido',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubes.evento'),
            preserve_default=False,
        ),
    ]
