# Generated by Django 5.0 on 2024-11-18 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0003_club_miembros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='miembros',
        ),
    ]
