# Generated by Django 5.0 on 2024-11-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_eventoasistido_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoasistido',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='eventoasistido',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='eventoasistido',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/eventos_asistidos/'),
        ),
    ]
