# Generated by Django 5.0 on 2024-11-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0005_club_miembros'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudclub',
            name='correo',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
